language: rust

rust:
  - 1.26.0
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: stable
      before_script:
        - rustup component add rustfmt-preview
      script:
        - cargo fmt --all -- --check
        - cargo build --verbose
        - cargo test --verbose

script:
  - cargo build --verbose
  - cargo test --verbose
