[package]
name = "yaraio"
version = "0.1.0"
authors = ["Min Kim <msk@dolbo.net>"]
build = "build.rs"

[dependencies]
bitflags = "1"
lalrpop-util = "0.16"
regex = "1"

[build-dependencies]
lalrpop = "0.16"
